"""Lesson management module."""

from .types import (
    ArticleStage,
    VideoStage,
    ChatStage,
    Stage,
    Lesson,
)
from .loader import (
    load_lesson,
    get_available_lessons,
    LessonNotFoundError,
)
from .content import (
    load_article,
    extract_article_section,
    load_video_transcript,
    load_video_transcript_with_metadata,
    load_article_with_metadata,
    ArticleContent,
    ArticleMetadata,
    VideoTranscriptContent,
    VideoTranscriptMetadata,
    get_stage_title,
    get_stage_duration,
)
from .sessions import (
    create_session,
    get_session,
    get_user_sessions,
    add_message,
    advance_stage,
    complete_session,
    claim_session,
    get_user_lesson_progress,
    SessionNotFoundError,
    SessionAlreadyClaimedError,
)
from .chat import send_message as send_lesson_message, get_stage_content
from .llm import DEFAULT_PROVIDER
from .course_loader import (
    load_course,
    get_next_lesson,
    get_all_lesson_slugs,
    get_lessons,
    get_required_lessons,
    get_due_by_meeting,
    CourseNotFoundError,
)

__all__ = [
    "ArticleStage",
    "VideoStage",
    "ChatStage",
    "Stage",
    "Lesson",
    "load_lesson",
    "get_available_lessons",
    "LessonNotFoundError",
    "load_article",
    "extract_article_section",
    "load_video_transcript",
    "load_video_transcript_with_metadata",
    "load_article_with_metadata",
    "ArticleContent",
    "ArticleMetadata",
    "VideoTranscriptContent",
    "VideoTranscriptMetadata",
    "get_stage_title",
    "get_stage_duration",
    "create_session",
    "get_session",
    "get_user_sessions",
    "add_message",
    "advance_stage",
    "complete_session",
    "claim_session",
    "get_user_lesson_progress",
    "SessionNotFoundError",
    "SessionAlreadyClaimedError",
    "send_lesson_message",
    "get_stage_content",
    "DEFAULT_PROVIDER",
    "load_course",
    "get_next_lesson",
    "get_all_lesson_slugs",
    "get_lessons",
    "get_required_lessons",
    "get_due_by_meeting",
    "CourseNotFoundError",
]
