"""Module management package."""

from .types import (
    ArticleStage,
    VideoStage,
    ChatStage,
    Stage,
    Module,
    NarrativeModule,
    NarrativeSection,
    NarrativeSegment,
    TextSection,
    ArticleSection,
    VideoSection,
    TextSegment,
    ArticleExcerptSegment,
    VideoExcerptSegment,
)
from .loader import (
    load_module,
    load_narrative_module,
    get_available_modules,
    ModuleNotFoundError,
)
from .content import (
    load_article,
    extract_article_section,
    load_video_transcript,
    load_video_transcript_with_metadata,
    load_article_with_metadata,
    bundle_narrative_module,
    ArticleContent,
    ArticleMetadata,
    VideoTranscriptContent,
    VideoTranscriptMetadata,
    get_stage_title,
    get_stage_duration,
)
from .chat import send_module_message, get_stage_content
from .llm import DEFAULT_PROVIDER
from .course_loader import (
    load_course,
    get_next_module,
    get_all_module_slugs,
    get_modules,
    get_required_modules,
    get_due_by_meeting,
    CourseNotFoundError,
)

__all__ = [
    "ArticleStage",
    "VideoStage",
    "ChatStage",
    "Stage",
    "Module",
    "NarrativeModule",
    "NarrativeSection",
    "NarrativeSegment",
    "TextSection",
    "ArticleSection",
    "VideoSection",
    "TextSegment",
    "ArticleExcerptSegment",
    "VideoExcerptSegment",
    "load_module",
    "load_narrative_module",
    "get_available_modules",
    "ModuleNotFoundError",
    "load_article",
    "extract_article_section",
    "load_video_transcript",
    "load_video_transcript_with_metadata",
    "load_article_with_metadata",
    "bundle_narrative_module",
    "ArticleContent",
    "ArticleMetadata",
    "VideoTranscriptContent",
    "VideoTranscriptMetadata",
    "get_stage_title",
    "get_stage_duration",
    "send_module_message",
    "get_stage_content",
    "DEFAULT_PROVIDER",
    "load_course",
    "get_next_module",
    "get_all_module_slugs",
    "get_modules",
    "get_required_modules",
    "get_due_by_meeting",
    "CourseNotFoundError",
]
