"""add assessment_responses and assessment_scores tables

Revision ID: 0ef080fc2fd5
Revises: b47d38653ec5
Create Date: 2026-02-14 12:06:39.331543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ef080fc2fd5'
down_revision: Union[str, None] = 'b47d38653ec5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_responses',
    sa.Column('response_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('anonymous_token', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Text(), nullable=False),
    sa.Column('module_slug', sa.Text(), nullable=False),
    sa.Column('learning_outcome_id', sa.Text(), nullable=True),
    sa.Column('content_id', sa.UUID(), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('answer_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_assessment_responses_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('response_id', name=op.f('pk_assessment_responses'))
    )
    op.create_index('idx_assessment_responses_anon', 'assessment_responses', ['anonymous_token'], unique=False)
    op.create_index('idx_assessment_responses_module', 'assessment_responses', ['module_slug'], unique=False)
    op.create_index('idx_assessment_responses_question', 'assessment_responses', ['question_id'], unique=False)
    op.create_index('idx_assessment_responses_user_id', 'assessment_responses', ['user_id'], unique=False)
    op.create_table('assessment_scores',
    sa.Column('score_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('score_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_id', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['response_id'], ['assessment_responses.response_id'], name=op.f('fk_assessment_scores_response_id_assessment_responses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('score_id', name=op.f('pk_assessment_scores'))
    )
    op.create_index('idx_assessment_scores_response_id', 'assessment_scores', ['response_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop assessment_scores first (FK dependency on assessment_responses)
    op.drop_index('idx_assessment_scores_response_id', table_name='assessment_scores')
    op.drop_table('assessment_scores')
    op.drop_index('idx_assessment_responses_user_id', table_name='assessment_responses')
    op.drop_index('idx_assessment_responses_question', table_name='assessment_responses')
    op.drop_index('idx_assessment_responses_module', table_name='assessment_responses')
    op.drop_index('idx_assessment_responses_anon', table_name='assessment_responses')
    op.drop_table('assessment_responses')
    # ### end Alembic commands ###
