"""rename first_name last_name to nickname

Revision ID: 39e3de01c3b8
Revises: 001
Create Date: 2025-12-10 10:22:21.616419

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "39e3de01c3b8"
down_revision: Union[str, None] = "001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("nickname", sa.Text(), nullable=True))
    # Copy existing first_name data to nickname before dropping
    op.execute("UPDATE users SET nickname = first_name")
    op.drop_column("users", "first_name")
    op.drop_column("users", "last_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("last_name", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "users", sa.Column("first_name", sa.TEXT(), autoincrement=False, nullable=True)
    )
    # Copy nickname back to first_name before dropping
    op.execute("UPDATE users SET first_name = nickname")
    op.drop_column("users", "nickname")
    # ### end Alembic commands ###
