# educational_content/courses/default.yaml
slug: default
title: AI Safety Fundamentals

progression:
  - lesson: introduction
  - meeting: 1
  - lesson: coming-soon
  - lesson: coming-soon
  - meeting: 2
  - lesson: coming-soon
  - meeting: 3
  - lesson: coming-soon
  - meeting: 4
# - lesson: xxxx
#   optional: true (this makes the above lesson optional)
#   (note: you can also have optional articles/videos within lessons)
# - meeting: 2
# - lesson : yyyy
# - meeting: 3
# etc
